### ISSUE TITLE
can't get the program to run on Ubuntu 20.04

### ISSUE THREAD

**Issue by TheAquabat** [wepiha/qt-amdgpu-fan-ctl#3]
seems on Ubuntu 20.04 python packages are different there must be something I'm missing because the app crashes this is the log in terminal 
```

Loaded config.json: {'card': '0', 'points': [[0, 0], [39, 0], [40, 40], [65, 100]], 'interval': '2500', 'logging': False}
Traceback (most recent call last):
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 306, in <module>
    main()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 300, in main
    my_mainWindow = MainWindow()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 29, in __init__
    self._init_graphview()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 77, in _init_graphview
    self._init_graph_lines()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 111, in _init_graph_lines
    lineCurrTemp = pg.InfiniteLine(pos=0, pen=pen, name='currTemp', angle=270)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/InfiniteLine.py", line 84, in __init__
    self.setPos(pos)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/InfiniteLine.py", line 233, in setPos
    raise Exception("Must specify 2D coordinate for non-orthogonal lines
```

**Comment by wepiha** [comment]
This should be fixed with the latest commit.

**Comment by TheAquabat** [comment]
now I'm getting a different error

```
Loaded config.json: {'card': '0', 'points': [[0, 0], [39, 0], [40, 40], [65, 100]], 'interval': '2500', 'logging': False}
Traceback (most recent call last):
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 306, in <module>
    main()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 300, in main
    my_mainWindow = MainWindow()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 29, in __init__
    self._init_graphview()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 78, in _init_graphview
    self._init_graph_legend()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 138, in _init_graph_legend
    self.ui.graphicsView.addItem(legendItem)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 485, in addItem
    self.vb.addItem(item, *args, **vbargs)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 407, in addItem
    item.setParentItem(self.childGroup)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/LegendItem.py", line 127, in setParentItem
    offset = Point(self.opts['offset'])
  File "/usr/lib/python3/dist-packages/pyqtgraph/Point.py", line 35, in __init__
    QtCore.QPointF.__init__(self, *args)
TypeError: arguments did not match any overloaded call:
  QPointF(): too many arguments
  QPointF(float, float): argument 1 has unexpected type 'NoneType'
  QPointF(QPoint): argument 1 has unexpected type 'NoneType'
  QPointF(QPointF): argument 1 has unexpected type 'NoneType'
```

**Comment by wepiha** [comment]
Updated with a new commit to match pyqtgraph requirements. Sorry I am not at my dev workstation at the moment and can only reply by mobile (hence why you may be seeing errors).

**Comment by TheAquabat** [comment]
now a different error

```
Traceback (most recent call last):
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 305, in <module>
    main()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 299, in main
    my_mainWindow = MainWindow()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 29, in __init__
    self._init_graphview()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 78, in _init_graphview
    self._init_graph_legend()
  File "/usr/local/qt-amdgpu-fan-ctl/qt-amdgpu-fan-ctl.py", line 137, in _init_graph_legend
    self.ui.graphicsView.addItem(legendItem)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 485, in addItem
    self.vb.addItem(item, *args, **vbargs)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 407, in addItem
    item.setParentItem(self.childGroup)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/LegendItem.py", line 131, in setParentItem
    self.anchor(itemPos=anchor, parentPos=anchor, offset=offset)
  File "/usr/lib/python3/dist-packages/pyqtgraph/graphicsItems/GraphicsWidgetAnchor.py", line 44, in anchor
    parent.geometryChanged.connect(self.__geometryChanged)
AttributeError: 'ChildGroup' object has no attribute 'geometryChanged'
```

**Comment by wepiha** [comment]
I have made a workaround with the latest commit. I will look at fixing this when time permits.

**Comment by TheAquabat** [comment]
now it's working closing thanks
