### ISSUE TITLE
module 'PyQt5.QtGui' has no attribute 'QVBoxLayout'

### ISSUE THREAD

**Issue by stapler8** [wepiha/qt-amdgpu-fan-ctl#4]
I'm trying to run this on Ubuntu 20.04

```
sudo python3 ./qt-amdgpu-fan-ctl.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Loaded config.json: {'card': '0', 'points': [[0, 0], [39, 0], [40, 40], [65, 100]], 'interval': '2500', 'logging': False}
Done!
Trying to set file owner... Error! Failed to chown, the error was:
[Errno 2] No such file or directory: 'file.tmp'
*************************************************************
INFO:common.hwmonInterface:__setvalue(device/power_dpm_force_performance_level, auto)::success
Traceback (most recent call last):
  File "./qt-amdgpu-fan-ctl.py", line 305, in <module>
    main()
  File "./qt-amdgpu-fan-ctl.py", line 299, in main
    my_mainWindow = MainWindow()
  File "./qt-amdgpu-fan-ctl.py", line 34, in __init__
    self._init_monitor_ui()
  File "./qt-amdgpu-fan-ctl.py", line 154, in _init_monitor_ui
    self.monwindow = MonitorWindow(self.hwmon)
  File "/home/alex/Documents/amdgraph/qt-amdgpu-fan-ctl/ui/monitorwindow.py", line 29, in __init__
    self._init_layout()
  File "/home/alex/Documents/amdgraph/qt-amdgpu-fan-ctl/ui/monitorwindow.py", line 40, in _init_layout
    layout = QtGui.QVBoxLayout(self.centralwidget)
AttributeError: module 'PyQt5.QtGui' has no attribute 'QVBoxLayout'
```

Is there anything I can do to remedy this?

**Comment by wepiha** [comment]
Hi there,

 I have updated mainwindow.py references to what were PyQt4 to PyQt5. 

Please let me know if that helps!

**Comment by stapler8** [comment]
Thanks for the speedy response! I'm getting a new error now:

```
sudo python3 ./qt-amdgpu-fan-ctl.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Loaded config.json: {'card': '0', 'points': [[0, 0], [39, 0], [40, 40], [65, 100]], 'interval': '2500', 'logging': False}
Done!
Trying to set file owner... Error! Failed to chown, the error was:
[Errno 2] No such file or directory: 'file.tmp'
*************************************************************
INFO:common.hwmonInterface:__setvalue(device/power_dpm_force_performance_level, auto)::success
Traceback (most recent call last):
  File "./qt-amdgpu-fan-ctl.py", line 305, in <module>
    main()
  File "./qt-amdgpu-fan-ctl.py", line 299, in main
    my_mainWindow = MainWindow()
  File "./qt-amdgpu-fan-ctl.py", line 37, in __init__
    self._timer_update_tick()
  File "./qt-amdgpu-fan-ctl.py", line 198, in _timer_update_tick
    self._refresh_main_ui()
  File "./qt-amdgpu-fan-ctl.py", line 276, in _refresh_main_ui
    self.ui.labelPowerProfile.setText(self.hwmon.pp_power_profile_mode_active.mode_name.title())
  File "/home/alex/Documents/amdgraph/qt-amdgpu-fan-ctl/common/hwmonInterface.py", line 561, in pp_power_profile_mode_active
    for profile in self.pp_power_profile_list:
  File "/home/alex/Documents/amdgraph/qt-amdgpu-fan-ctl/common/hwmonInterface.py", line 552, in pp_power_profile_list
    result.append ( pp_power_profile(line.split()) )
  File "/home/alex/Documents/amdgraph/qt-amdgpu-fan-ctl/common/hwmonInterface.py", line 174, in __init__
    "MCLK_DOWN_HYST" : data[7],
IndexError: list index out of range
```
